# config/train_teacher.yaml
defaults:
  - _self_

# データ関連
data:
  root_dir: ???   # 環境変数 or コマンドライン上書き
  seq_len: 8
  batch_size: 32
  num_workers: 4

# モデル・VAE
vae:
  ckpt: "${env:VAE_CKPT}"
  latent_dim: 32                # VAE の潜在次元

# LSTM・TeacherModel
model:
  lstm_hidden: 128
  lstm_layers: 1
  waypoint_dim: 30
  action_dim: 2

# 学習設定
train:
  epochs: 20
  lr: 1e-4
  log_dir: "logs/train_teacher/"  # ログ出力先

# 出力
output:
  model_path: "teacher_model.pth"
